import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'inverse-on-surface': '#eaf1ff',
        tertiary: '#924700',
        'on-error-container': '#93000a',
        'surface-container': '#e5eeff',
        surface: '#f8f9ff',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        secondary: '#5c5f61',
        'on-primary-fixed': '#001a42',
        'on-secondary-container': '#626567',
        'surface-bright': '#f8f9ff',
        'on-tertiary-fixed': '#311400',
        'on-surface-variant': '#424754',
        'on-primary': '#ffffff',
        'secondary-container': '#e0e3e5',
        'on-secondary-fixed-variant': '#444749',
        'primary-fixed': '#d8e2ff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#adc6ff',
        'inverse-primary': '#adc6ff',
        'secondary-fixed': '#e0e3e5',
        'inverse-surface': '#213145',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-container': '#b75b00',
        'on-surface': '#0b1c30',
        'surface-container-highest': '#d3e4fe',
        'surface-container-low': '#eff4ff',
        'outline-variant': '#c2c6d6',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        outline: '#727785',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#191c1e',
        'on-background': '#0b1c30',
        primary: '#4f46e5',
        'secondary-fixed-dim': '#c4c7c9',
        'surface-dim': '#cbdbf5',
        'on-primary-fixed-variant': '#004395',
        'tertiary-fixed-dim': '#ffb786',
        'on-secondary': '#ffffff',
        background: '#f8f9ff',
        'surface-container-high': '#dce9ff',
        'surface-tint': '#005ac2',
        'on-tertiary-fixed-variant': '#723600',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'stack-lg': '32px',
        'stack-md': '16px',
        gutter: '24px',
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        'container-max': '1280px',
        base: '8px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        'headline-sm': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['Inter', 'system-ui', 'sans-serif'],
        'label-sm': ['Inter', 'system-ui', 'sans-serif'],
        'label-md': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}

export default config
